### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-node03#1]
- [x] czy widzisz jakiś sposób na podmianę całego switcha w pliku `server.js` i nieco lepszą, bardziej generyczną wersję obsługi routingu?
- [x] pamiętaj, że jeśli rzucasz błędami za pomocą `throw` to musisz opakować blok kodu wykonującego tę instrukcje takim blokiem:
``` js
try {
    // kod, ktory potencjalnie moze wyrzucic blad
} catch(err) {
    console.error(err) // przechwycenie i obsługa błędu
}
```
- [x] nie wszędzie obsługujesz błąd próby odczytu pliku (metoda `fs.readFile`)
- [x] upload coś nie za bardzo chce mi działać :(

widzę, że korzystasz z szablonów ejs. Bardzo fajnie :)
dropzone też bardzo spoko.

**Comment by patmaz** [comment]
na branchu websockets: https://github.com/patmaz/js-bootcamp-node03/commit/6a19541c752b101f635081c661632c3c952838da
1 - switch zastąpiłem IIFE
2 - ok, teraz załapałem :)
3 - poprawione
4 - błąd prawdopodobnie spowodowany brakiem folderu `uploads`, załatwione w `.gitignore`

Dzięki!

**Comment by patmaz** [comment]
Eh te `try cacth`: https://github.com/patmaz/js-bootcamp-node03/commit/6b731f8a91e5317d4b0bb534ab06f79369b06198
